name: "gemma_torch"
backend: "python"

input {
  name: "input_token_ids"
  data_type: TYPE_INT32
  dims: [ -1 ]
}
output {
  name: "output_token_ids"
  data_type: TYPE_INT32
  dims: [ 1, 1, -1]
}

parameters {
  key: "model_dir"
  value: {
    string_value: "/wsc2025/checkpoints/google/gemma-3-1b-it/"
  }
}

instance_group {
  count: 1
  kind: KIND_GPU
}
