name: "postprocessing"
backend: "python"

input {
  name: "token_ids"
  data_type: TYPE_INT32
  dims: [ 1, 1, -1]
  reshape: { shape: [ -1 ] }
}

output {
  name: "decoded_text"
  data_type: TYPE_STRING
  dims: [ 1 ]
}

parameters {
  key: "tokenizer_dir"
  value: {
    string_value: "/wsc2025/checkpoints/google/gemma-3-1b-it/"
  }
}

instance_group {
  count: 1
  kind: KIND_CPU
}

