{
 "title": "Web Summer Camp 2025 Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU utiliziation history",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 1 },
   "targets": [
    { "expr": "nv_gpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU util",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_gpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory allocated history",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    { "expr": "nv_cpu_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_cpu_memory_used_bytes / nv_cpu_memory_total_bytes * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "GPU memory history",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    { "expr": "nv_gpu_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU memory %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes / nv_gpu_memory_total_bytes * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "ensemble_torch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nv_inference_count{model=\"ensemble_torch\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Composite latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us{model=\"ensemble_torch\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_input_duration_us{model=\"ensemble_torch\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_infer_duration_us{model=\"ensemble_torch\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_output_duration_us{model=\"ensemble_torch\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ensemble_trt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nv_inference_count{model=\"ensemble_trt\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Composite latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us{model=\"ensemble_trt\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_input_duration_us{model=\"ensemble_trt\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_infer_duration_us{model=\"ensemble_trt\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_output_duration_us{model=\"ensemble_trt\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "preprocessing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "model" },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nv_inference_count{model=\"preprocessing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Composite latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us{model=\"preprocessing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_input_duration_us{model=\"preprocessing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_infer_duration_us{model=\"preprocessing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_output_duration_us{model=\"preprocessing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "gemma_torch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nv_inference_count{model=\"gemma_torch\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Composite latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us{model=\"gemma_torch\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_input_duration_us{model=\"gemma_torch\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_infer_duration_us{model=\"gemma_torch\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_output_duration_us{model=\"gemma_torch\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "tensorrt_llm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nv_inference_count{model=\"tensorrt_llm\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Composite latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us{model=\"tensorrt_llm\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_input_duration_us{model=\"tensorrt_llm\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_infer_duration_us{model=\"tensorrt_llm\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_output_duration_us{model=\"tensorrt_llm\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "postprocessing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nv_inference_count{model=\"postprocessing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Composite latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us{model=\"postprocessing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_input_duration_us{model=\"postprocessing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_infer_duration_us{model=\"postprocessing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_compute_output_duration_us{model=\"postprocessing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}